name: FurnaceCommand
main: NewPlayerMC\Main
api: 5.0.0
version: 2.0.0
author: NewPlayerMC

permissions:
  furnace.use:
    default: op
    description: Allow to /furnace
  furnace.all:
    default: op
    description: Allow to /furnace all