---
# command description
command_description: "Melt your items"

# message when player doesn't have the permission to use the command
permission_message: "You don't have the permission to use this command !"

# messages
furnace_message: "Your item has been furnaced"
furnace_all_message: "All your items have been furnaced"

item_not_furnacable: "You cannot furnace this item"

# Cooldown in seconds
cooldown: 10

# Cooldown message
cooldown_message: "§cYou are currently in cooldown, please wait {cooldown} seconds"

...